# ------------------------------------------------------------------------------
# init.yml
# ------------------------------------------------------------------------------

---

- hosts: dev,gateway,prod3,prod4

  # Prompt for the subdomain to act upon; for example "dev", "test", "www", etc.
  # This playbook is restricted to act upon a single subdomain on each run.

  vars_prompt:

    - name: subdomain
      prompt: What is the subdomain?
      private: false

  tasks:

    - ansible.builtin.script:
        chdir: /var/www/{{ subdomain }}.{{ domain_name }}/html
        cmd: wordpress/wp-scripts/init.sh
        executable: bash
      become: yes
      become_user: www-data
